config/routes.rb
Rails.application.routes.draw do
  
  constraints subdomain: false do
    get ':any', to: redirect(subdomain: 'www', path: '/%{any}'), any: /.*/
  end

  root to: 'landing_page#index'
  # sitemap
  get 'sitemap.xml', to: 'sitemaps#index'
  #
  post 'subscribe', to: 'landing_page#subscribe'
  post 'contact', to: 'landing_page#contact'
  post 'subscribe', to: 'landing_page#subscribe'
  post 'suscribe_location', to: 'landing_page#suscribe_location'
  resources :menus, only: [:index, :show]
  post '/rate' => 'rater#create', :as => 'rate'
  # Static Pages
  get 'contact', to: 'static_pages#contact'
  get 'contact/cookers', to: 'static_pages#contact_cookers'
  get 'contact/service', to: 'static_pages#contact_service'
  get 'contact/general', to: 'static_pages#contact_general'
  get 'about_us', to: 'static_pages#about_us'
  get 'legal', to: 'static_pages#legal'
  get 'company', to: 'static_pages#company'
  get 'help', to: 'static_pages#help'
  get 'block_sale', to: 'static_pages#block_sale'

  # Devise Users
  devise_for :users, controllers: { passwords: 'users/passwords' }, skip: [:registrations, :sessions]
  devise_scope :user do
    delete '/logout', to: 'users/sessions#destroy', as: :destroy_user_session
    get '/login', to: 'users/sessions#new', as: :new_user_session
    post '/login', to: 'users/sessions#create', as: :user_session
  end
  devise_for :households, controllers: { registrations: 'households/registrations' }, skip: :sessions
  devise_for :general_users, controllers: { registrations: 'general_users/registrations' }, skip: :sessions

  # Households
  resources :households, only: [:show] do
    resources :delivery_areas, controller: 'households/delivery_areas'
    resources :orders, controller: 'households/orders', skip: [:new, :edit]
    post '/orders/:order_id/deliver', to: 'households/orders#deliver', as: :order_deliver
    resources :dishes, controller: 'households/dishes'
    resources :menus, controller: 'households/menus'
  end

  # General Users
  resources :general_users, only: [:show] do
    resources :orders, controller: 'general_users/orders'
  end

  # Payments
  namespace :payments do
    resource :credit_card, controller: 'credit_card', only: [:new, :create]
    resource :paypal, controller: 'paypal', only: [:create]
    get 'paypal/paypalconfirm', to: 'paypal#paypal_confirm', as: :paypal_confirm
    post 'paypal/paypalconfirmwebhook', to: 'paypal#paypal_confirm_webhook', as: :paypal_confirm_webhook
  end

  # Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/controllers/households/confirmations_controller.rb
class Households::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/households/delivery_areas_controller.rb
class Households::DeliveryAreasController < ApplicationController
  before_action :require_household!, except: [:show, :index]

  def index
    @delivery_areas = current_household.delivery_areas
  end

  def new
    @delivery_area = current_household.delivery_areas.build
  end

  def edit
    set_delivery_area
  end

  def show
    set_delivery_area
  end

  def create
    @delivery_area = current_household.delivery_areas.build(delivery_area_params)
    if @delivery_area.save
      redirect_to household_delivery_areas_path(current_user), notice: 'Delivery area was successfully created.'
    else
      render :new
    end
  end

  def update
    set_delivery_area
    if @delivery_area.update delivery_area_params
      redirect_to [current_user, @delivery_area], notice: 'Delivery area was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    set_delivery_area
    @delivery_area.destroy
    redirect_to household_delivery_areas_path(current_user), notice: 'Dish was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_delivery_area
    @delivery_area = DeliveryArea.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def delivery_area_params
    params.require(:delivery_area).permit(
      :name,
      :latitude,
      :longitude,
      :address,
      :radius,
      :delivery_area_id,
      :household_id,
      :tmp_location_id)
  end
end

app/controllers/households/dishes_controller.rb
class Households::DishesController < ApplicationController
  before_action :require_household!, except: [:show, :index]
  before_action :set_dish, only: [:show]
  before_action :set_own_dish, only: [:edit, :update, :destroy]

  # GET /households/:household_id/dishes
  # GET /households/:household_id/dishes.json
  def index
    @dishes = Dish.for_household(household)
  end

  # GET /households/:household_id/dishes/:id
  # GET /households/:household_id/dishes/:id.json
  def show
  end

  # GET /households/:household_id/dishes/new
  def new
    @dish = current_household.dishes.build
  end

  # GET /households/:household_id/dishes/1/edit
  def edit
  end

  # POST /households/:household_id/dishes
  # POST /households/:household_id/dishes.json
  def create
    @dish = current_household.dishes.build(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to [current_user, @dish], notice: 'Dish was successfully created.' }
        format.json { render json: @dish, status: :created }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /households/:household_id/dishes/1
  # PATCH/PUT /households/:household_id/dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to [current_user, @dish], notice: 'Dish was successfully updated.' }
        format.json { render json: @dish, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /households/:household_id/dishes/1
  # DELETE /households/:household_id/dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to household_dishes_url(current_user), notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_dish
    @dish = household.dishes.find(params[:id])
  end

  def set_own_dish
    @dish = current_household.dishes.find(params[:id])
  end

  def household
    Household.find(params[:household_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dish_params
    params.require(:dish).permit(:name, :description, :price, :calories_level, :fat_level, :spice_level, :household_id, :image)
  end
end

app/controllers/households/menus_controller.rb
class Households::MenusController < ApplicationController
  before_action :require_household!
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.households(household, params[:page]).decorate
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    @orders = Order.in_menu(@menu, params[:page]).decorate
  end

  # GET /menus/new
  def new
    @menu = household.menus.new.decorate
    @dishes = Dish.for_household(household)
    @delivery_areas = household.delivery_areas
  end

  # GET /menus/1/edit
  def edit
    @dishes = Dish.for_household(household)
    @delivery_areas = household.delivery_areas
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = household.menus.build(menu_params).decorate
    @dishes = Dish.for_household(household)
    @delivery_areas = household.delivery_areas

    if @menu.save
      redirect_to [current_user, @menu], notice: 'Menu was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    @dishes = Dish.for_household(household)
    respond_to do |format|
      if @menu.update(menu_params.except(:main_dish_id, :dish_ids))
        format.html { redirect_to [current_user, @menu], notice: 'Menu was successfully updated.' }
        format.json { render json: @menu, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to household_menus_url(current_user), notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_menu
    @menu = Menu.find(params[:id]).decorate
  end

  def household
    Household.find(params[:household_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def menu_params
    params.require(:menu).permit(:description,
                                 :delivery_eta,
                                 :household_id,
                                 :delivery_area_id,
                                 :raw_price,
                                 :quantity,
                                 :main_dish_id,
                                 :block_sale,
                                 dish_ids: [])
  end
end

app/controllers/households/omniauth_callbacks_controller.rb
class Households::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/households/orders_controller.rb
class Households::OrdersController < ApplicationController
  before_action :require_household!
  before_action :set_order, only: [:show]
  before_action :set_own_order, only: [:edit, :update, :destroy]

  # GET /households/:household_id/orders
  # GET /households/:household_id/orders.json
  def index
    @orders = Order.households(current_household, params).decorate
  end

  # GET /households/:household_id/orders/1
  # GET /households/:household_id/orders/1.json
  def show
  end

  # GET /households/:household_id/orders/new
  def new
    @order = household.orders.build
  end

  # GET /households/:household_id/orders/1/edit
  def edit
  end

  # POST /households/:household_id/orders
  # POST /households/:household_id/orders.json
  def create
    @order = household.orders.build(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to [current_user, @order], notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /households/:household_id/orders/1
  # PATCH/PUT /households/:household_id/orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to [current_user, @order], notice: 'Order was successfully updated.' }
        format.json { render json: @order, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /households/:household_id/orders/1
  # DELETE /households/:household_id/orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to household_orders_url(current_user), notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #### Sub elements

  # POST /households/:household_id/orders/:order_id/deliver
  def deliver
    @order = current_household.orders.find(params[:order_id])
    @order.deliver
    if @order.save
      redirect_to [current_user, @order], notice: 'Order was successfully delivered.'
    else
      redirect_to [current_user, @order], notice: 'Order delivery was '\
      "unsuccessful: #{@order.errors.full_messages}"
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = household.orders.find(params[:id]).decorate
  end

  def set_own_order
    @order = current_household.orders.find(params[:id])
  end

  def household
    Household.find(params[:household_id])
  end

  # A list of the param names that can be used for filtering the orders list
  def filtering_params(params)
    params.slice(:state, :created_before, :created_after)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:page, :latitude, :longitude, :delivery_eta,
                                  :comment_food, :comment_order, :state, :user_id, :dish_id)
  end
end

app/controllers/households/passwords_controller.rb
class Households::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/households/registrations_controller.rb
class Households::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:first_name, :last_name, :phone, :avatar,
               :email, :password, :password_confirmation)
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:first_name, :last_name, :phone, :avatar,
               :email, :password, :password_confirmation, :current_password)
    end
  end

  def after_sign_up_path_for(resource)
    sign_in(resource)
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/menus_helper.rb
# ## Schema Information
#
# Table name: `menus`
#
# ### Columns
#
# Name                    | Type               | Attributes
# ----------------------- | ------------------ | ---------------------------
# **`id`**                | `integer`          | `not null, primary key`
# **`created_at`**        | `datetime`         | `not null`
# **`updated_at`**        | `datetime`         | `not null`
# **`date`**              | `date`             |
# **`household_id`**      | `integer`          |
# **`raw_price`**         | `decimal(16, 2)`   |
# **`quantity`**          | `integer`          |
# **`total_left`**        | `integer`          |
# **`delivery_eta`**      | `datetime`         |
# **`description`**       | `text`             |
# **`is_archived`**       | `boolean`          |
# **`charge`**            | `decimal(16, 2)`   |
# **`delivery_area_id`**  | `integer`          |
# **`block_sale`**        | `boolean`          |
#

module MenusHelper
  def menu_main_img_url(menu)
    menu.main_dish.image.url(:medium) if menu.main_dish
  end
end

app/views/households/menus/_form.html.erb
<%= form_for([current_user, menu]) do |f| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%# stuff related to dishes %>
  <% if dishes %>
  <% if menu.new_record? %> 

  <div class="form-group">
    <%= f.label :main_dish, t(:main_dish) %><br />
    <%= select_tag("menu[main_dish_id]", options_from_collection_for_select(dishes, :id, :name), class: "form-control") %>
  </div>
  <% end %>
  <% else %>
    <p>Aún no tienes platillos, crealos</p>
  <% end %>

  <div class="form-group">
    <%= f.label :description, t(:description) %><br />
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <p>
    <%= f.check_box :block_sale %> :block_sale
  </div>

  <div class="form-group select-date">
    <%= f.label :delivery_eta, t(:eta) %><br>
    <%= f.datetime_select :delivery_eta, :ampm => true, :minute_step => 15 %>
  </div>

  <div class="form-group">
    <%= f.label :delivery_area, t(:delivery_area) %><br>
    <%= select_tag("menu[delivery_area_id]", options_from_collection_for_select(
    delivery_areas, :id, :name, menu.delivery_area_id), class: "form-control") %>
  </div>

  <%= t(:price) %><br>
  <div class="form-group">
    <%= f.label :raw_price, "Neighbourfood agregara una comisión a la venta de $5.0 MXN mas 13%" %><br>
    <%= f.number_field :raw_price, :class => 'text_field', :step => 'any', 
    :value => (number_with_precision(menu.raw_price_simple, :precision => 2) || 0.00), class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :quantity, t(:quantity) %><br>
    <%= f.number_field :quantity, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit t(:create_menu), class: "btn btn-lg btn-default" %>
  </div>
<% end %>

app/views/households/menus/edit.html.erb
<div class="container">
<h1>Editing Menu</h1>

<%= render 'form', menu: @menu, dishes: @dishes, delivery_areas: @delivery_areas %>

<%= link_to t(:show), [current_user, @menu] %> |
<%= link_to t(:back), household_menus_path(current_user) %>
</div>

app/views/households/menus/index.html.erb
<div class="container">
<h1><%= t(:listing_menus, scope: :households) %></h1>

<% if current_household %>
  <%= link_to t(:new_menu, scope: :households), new_household_menu_path(current_user) %>
<% end %>

<% if @menus.any? %>

<div class="table-responsive">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Entrega</th>
      <th>Disponibles</th>
      <th>Precio</th>
      <th>Comisión</th>
      <th>Ganancias</th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= link_to menu.name, household_menu_path(params[:household_id], menu) %></td>
        <td><%= menu.pickup_eta_simple %> en <%= menu.pickup_place %></td>
        <td><%= menu.total_left %>/<%= menu.quantity %></td>
        <td><%= menu.price %></td>
        <td><%= menu.charge %></td>
        <td><%= menu.total_hh_sale %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<% else %>
  <p>Aún no tienes menus</p>
<% end %><%# ./if.menus.any %>

<%= paginate @menus %>
</div>

app/views/households/menus/new.html.erb
<div class="container">
<h1>Nuevo Menú</h1>

<%= render 'form', menu: @menu, dishes: @dishes, delivery_areas: @delivery_areas %>

<%= link_to t(:back), household_menus_path(current_user) %>
</div>

app/views/households/menus/show.html.erb
<div class="container menu-show">
<%# ----- House hold options ----- %>

<% if current_household %>
  <%= link_to 'Eliminar', [current_household, @menu], method: :delete, data: { confirm: 'Are you sure?' } %> |
  <%= link_to 'Editar', edit_household_menu_path(current_user, @menu) %> |
  <%= link_to 'Regresar', household_menus_path(current_user) %>
<% elsif current_user %>
  <%= link_to 'Order', new_general_user_order_path(current_user, 
    order: {menu_id: @menu.id, household_id: @menu.household.id}) %>
<% else %>
  <p><%= link_to "Regístrate", new_general_user_registration_path %> o <%= link_to "inicia sesión", new_user_session_path %> para ordenar</p>

<% end %>

<%# ----- House hold options ----- %>

<h1><%= @menu.name %></h1>
<% if @menu.block_sale %>
<P>*** LA VENTA DE ESTE MENU ESTA BLOQEUADA ***</P>
<% end %>

<img src="<%= menu_main_img_url(@menu) %>" alt=""><br>

<h3>Descripción</h3>
<p>
<%= @menu.description %>
</p>

<h3>Platillos en el menu</h3>
<p>
<% @menu.menu_dishes.each do |a| %>
    <%if a.dish %>
      <%= a.dish.name %><%= a.is_main_dish ? '* platillo principal' : nil %><br>
    <% end %>
<% end %>
</p>

<h3>Datos de entrega</h3>
<p>
<%= @menu.pickup_place %><br>
<%= @menu.pickup_place_address %><br>
<%= @menu.pickup_eta %><br>
</p>

<h3>Datos de venta</h3>
<p>
Cantidad: <%= @menu.quantity %><br>
Precio sin comisión: <%= @menu.raw_price %><br>
Comisión: <%= @menu.charge %><br>
Precio de venta final: <%= @menu.price %><br>
</p>

<h3>Ventas</h3>
<p>
Unidades vendidas: <%= @menu.number_sold %><br>
Ganancias: <%= @menu.total_hh_sale %><br>
</p>


<h3>Ordenes</h3>
<%= render 'households/orders/table', orders: @orders %>




</div>