config/routes.rb
Rails.application.routes.draw do
  
  constraints subdomain: false do
    get ':any', to: redirect(subdomain: 'www', path: '/%{any}'), any: /.*/
  end

  root to: 'landing_page#index'
  # sitemap
  get 'sitemap.xml', to: 'sitemaps#index'
  #
  post 'subscribe', to: 'landing_page#subscribe'
  post 'contact', to: 'landing_page#contact'
  post 'subscribe', to: 'landing_page#subscribe'
  post 'suscribe_location', to: 'landing_page#suscribe_location'
  resources :menus, only: [:index, :show]
  post '/rate' => 'rater#create', :as => 'rate'
  # Static Pages
  get 'contact', to: 'static_pages#contact'
  get 'contact/cookers', to: 'static_pages#contact_cookers'
  get 'contact/service', to: 'static_pages#contact_service'
  get 'contact/general', to: 'static_pages#contact_general'
  get 'about_us', to: 'static_pages#about_us'
  get 'legal', to: 'static_pages#legal'
  get 'company', to: 'static_pages#company'
  get 'help', to: 'static_pages#help'
  get 'block_sale', to: 'static_pages#block_sale'

  # Devise Users
  devise_for :users, controllers: { passwords: 'users/passwords' }, skip: [:registrations, :sessions]
  devise_scope :user do
    delete '/logout', to: 'users/sessions#destroy', as: :destroy_user_session
    get '/login', to: 'users/sessions#new', as: :new_user_session
    post '/login', to: 'users/sessions#create', as: :user_session
  end
  devise_for :households, controllers: { registrations: 'households/registrations' }, skip: :sessions
  devise_for :general_users, controllers: { registrations: 'general_users/registrations' }, skip: :sessions

  # Households
  resources :households, only: [:show] do
    resources :delivery_areas, controller: 'households/delivery_areas'
    resources :orders, controller: 'households/orders', skip: [:new, :edit]
    post '/orders/:order_id/deliver', to: 'households/orders#deliver', as: :order_deliver
    resources :dishes, controller: 'households/dishes'
    resources :menus, controller: 'households/menus'
  end

  # General Users
  resources :general_users, only: [:show] do
    resources :orders, controller: 'general_users/orders'
  end

  # Payments
  namespace :payments do
    resource :credit_card, controller: 'credit_card', only: [:new, :create]
    resource :paypal, controller: 'paypal', only: [:create]
    get 'paypal/paypalconfirm', to: 'paypal#paypal_confirm', as: :paypal_confirm
    post 'paypal/paypalconfirmwebhook', to: 'paypal#paypal_confirm_webhook', as: :paypal_confirm_webhook
  end

  # Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/general_user.rb
# ## Schema Information
#
# Table name: `users`
#
# ### Columns
#
# Name                          | Type               | Attributes
# ----------------------------- | ------------------ | ---------------------------
# **`id`**                      | `integer`          | `not null, primary key`
# **`email`**                   | `string`           | `default(""), not null`
# **`encrypted_password`**      | `string`           | `default(""), not null`
# **`reset_password_token`**    | `string`           |
# **`reset_password_sent_at`**  | `datetime`         |
# **`remember_created_at`**     | `datetime`         |
# **`sign_in_count`**           | `integer`          | `default(0), not null`
# **`current_sign_in_at`**      | `datetime`         |
# **`last_sign_in_at`**         | `datetime`         |
# **`current_sign_in_ip`**      | `string`           |
# **`last_sign_in_ip`**         | `string`           |
# **`created_at`**              | `datetime`         | `not null`
# **`updated_at`**              | `datetime`         | `not null`
# **`type`**                    | `string`           |
# **`avatar_file_name`**        | `string`           |
# **`avatar_content_type`**     | `string`           |
# **`avatar_file_size`**        | `integer`          |
# **`avatar_updated_at`**       | `datetime`         |
# **`first_name`**              | `string`           |
# **`last_name`**               | `string`           |
# **`phone`**                   | `string`           |
# **`latitude`**                | `decimal(10, 6)`   |
# **`longitude`**               | `decimal(10, 6)`   |
# **`tmp_location_id`**         | `integer`          |
#

class GeneralUser < User
  after_create :subscribe

  has_many :orders

  ratyrate_rater

  def subscribe
    Subscription.new.add_user(email: email,
                              name: name,
                              city: 'None',
                              phone: phone)
  end
end

app/controllers/general_users/confirmations_controller.rb
class GeneralUsers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/general_users/omniauth_callbacks_controller.rb
class GeneralUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/general_users/orders_controller.rb
class GeneralUsers::OrdersController < ApplicationController
  before_action :set_order, only: [:show, :update]

  def index
    @orders = Order.users(current_user, params[:page]).decorate
  end

  def show
    @menu = @order.menu
  end

  def create
    tmp_params = order_params.except(:payment_type)
    tmp_params[:comment_order] += get_address
    
    @order = Order.build_user_order(current_user, tmp_params)
    @menu = Menu.where(id: order_params[:menu_id]).includes(:household).first.decorate
    if @order.save
      op = OrderProcessor.new(@order, order_params)
      
      return redirect_to block_sale_path if op.block_sale?

      paypal_paths = { return: payments_paypal_confirm_path, 
                       cancel: payments_paypal_confirm_path}
      if op.do_paypal_payment paypal_paths
        return redirect_to op.payment.paypal_redirect_urls[:approval_url][:href]
      end
      if op.credit_card?
        return redirect_to new_payments_credit_card_path(payment: { order_id: @order.id })
      end
      render :new
    else
      render 'menus/show'
    end
  end

  def update
    logger.info order_update_params
    @menu = @order.menu
    if @order.update order_update_params
      redirect_to [current_user, @order], notice: '¡Orden calificada con éxito!'
    else
      redirect_to [current_user, @order], notice: @order.errors
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = current_user.orders.find params[:id]
  end

  def get_address
    "Dirección: 
    Calle: #{params[:addr_street]}, 
    no. Exterior: #{params[:addr_ext_no]}, 
    no. interior: #{params[:addr_int_no]}, 
    Entre calles: #{params[:addr_bt_streets]}. \n"
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:latitude, :longitude, :delivery_eta,
                                  :comment_food, :comment_order, :state,
                                  :user_id, :menu_id, :household_id,
                                  :payment_type, :t_and_c_acepted, :quantity)
  end

  def order_update_params
    params.require(:order).permit(:comment_rate, :comment_order, :comment_food)
  end
end

app/controllers/general_users/passwords_controller.rb
class GeneralUsers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/general_users/registrations_controller.rb
class GeneralUsers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:first_name, :last_name, :phone,
               :email, :password, :password_confirmation)
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:first_name, :last_name, :phone,
               :email, :password, :password_confirmation, :current_password)
    end
  end

  def after_sign_up_path_for(resource)
    sign_in(resource)
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/general_users_controller.rb
# ## Schema Information
#
# Table name: `users`
#
# ### Columns
#
# Name                          | Type               | Attributes
# ----------------------------- | ------------------ | ---------------------------
# **`id`**                      | `integer`          | `not null, primary key`
# **`email`**                   | `string`           | `default(""), not null`
# **`encrypted_password`**      | `string`           | `default(""), not null`
# **`reset_password_token`**    | `string`           |
# **`reset_password_sent_at`**  | `datetime`         |
# **`remember_created_at`**     | `datetime`         |
# **`sign_in_count`**           | `integer`          | `default(0), not null`
# **`current_sign_in_at`**      | `datetime`         |
# **`last_sign_in_at`**         | `datetime`         |
# **`current_sign_in_ip`**      | `string`           |
# **`last_sign_in_ip`**         | `string`           |
# **`created_at`**              | `datetime`         | `not null`
# **`updated_at`**              | `datetime`         | `not null`
# **`type`**                    | `string`           |
# **`avatar_file_name`**        | `string`           |
# **`avatar_content_type`**     | `string`           |
# **`avatar_file_size`**        | `integer`          |
# **`avatar_updated_at`**       | `datetime`         |
# **`first_name`**              | `string`           |
# **`last_name`**               | `string`           |
# **`phone`**                   | `string`           |
# **`latitude`**                | `decimal(10, 6)`   |
# **`longitude`**               | `decimal(10, 6)`   |
# **`tmp_location_id`**         | `integer`          |
#

class GeneralUsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/controllers/households/orders_controller.rb
class Households::OrdersController < ApplicationController
  before_action :require_household!
  before_action :set_order, only: [:show]
  before_action :set_own_order, only: [:edit, :update, :destroy]

  # GET /households/:household_id/orders
  # GET /households/:household_id/orders.json
  def index
    @orders = Order.households(current_household, params).decorate
  end

  # GET /households/:household_id/orders/1
  # GET /households/:household_id/orders/1.json
  def show
  end

  # GET /households/:household_id/orders/new
  def new
    @order = household.orders.build
  end

  # GET /households/:household_id/orders/1/edit
  def edit
  end

  # POST /households/:household_id/orders
  # POST /households/:household_id/orders.json
  def create
    @order = household.orders.build(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to [current_user, @order], notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /households/:household_id/orders/1
  # PATCH/PUT /households/:household_id/orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to [current_user, @order], notice: 'Order was successfully updated.' }
        format.json { render json: @order, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /households/:household_id/orders/1
  # DELETE /households/:household_id/orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to household_orders_url(current_user), notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #### Sub elements

  # POST /households/:household_id/orders/:order_id/deliver
  def deliver
    @order = current_household.orders.find(params[:order_id])
    @order.deliver
    if @order.save
      redirect_to [current_user, @order], notice: 'Order was successfully delivered.'
    else
      redirect_to [current_user, @order], notice: 'Order delivery was '\
      "unsuccessful: #{@order.errors.full_messages}"
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = household.orders.find(params[:id]).decorate
  end

  def set_own_order
    @order = current_household.orders.find(params[:id])
  end

  def household
    Household.find(params[:household_id])
  end

  # A list of the param names that can be used for filtering the orders list
  def filtering_params(params)
    params.slice(:state, :created_before, :created_after)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:page, :latitude, :longitude, :delivery_eta,
                                  :comment_food, :comment_order, :state, :user_id, :dish_id)
  end
end

app/views/general_users/orders/_form.html.erb
<fieldset>
<%= form_for([current_user, order]) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag "order[delivery_eta]", order.menu.delivery_eta %>
  <%= hidden_field_tag "order[menu_id]", order.menu_id %>
  <%= hidden_field_tag "order[household_id]", order.household_id %>
  <%= hidden_field_tag "order[user_id]", current_user %>

  <p>Recuerda que solo se reciben pedidos hasta una hora antes de la hora de entrega</p>

  <p>Si quieres pagar en efectivo por favor usa whatsapp ((33) 1951 3411) o inbox</p>

  <h3>Domicilio</h3>

  <div class=row>
    <div class="col-sm-6">
      <div class="form-group">
        <%= text_field_tag 'addr_street', nil, placeholder: 'Calle', class: "form-control", required: true %>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="form-group">
        <%= text_field_tag 'addr_ext_no', nil, placeholder: 'Exterior', class: "form-control", required: true %>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="form-group">
        <%= text_field_tag 'addr_int_no', nil, placeholder: 'Interior', class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="form-group">
        <%= text_field_tag 'addr_bt_streets', nil, placeholder: 'Entre calles', class: "form-control" %>
      </div>
    </div>
  </div>


  <h3>Cantidad de órdenes</h3>

  <div class="form-group">
    <%= f.label :quantity, 'Número de platillos' %><br>
    <%= select_tag('order[quantity]', options_for_select(1..order.menu.total_left), class: "form-control") %>
  </div>

  <h3>Comentarios</h3>

  <div class="form-group">
    <%= f.label :comment_food, t(:comment_food) %><br>
    <%= f.text_area :comment_food, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :comment_order, t(:comment_order) %><br>
    <%= f.text_area :comment_order, class: "form-control" %>
  </div>


  <h3>Pago</h3>

  <div class="form-group">
    <%= f.label :payment_type, t(:payment_type) %><br>
    <p>Por ahora solo soportamos paypal pero estamso trabajando para mejorar y 
      aumentar las opciones.</p>
    <%= select_tag('order[payment_type]', options_for_select(
    [['paypal', 'paypal']]), class: "form-control") %>
    <!-- , ['tarjeta de crédito', 'credit_card'] -->
  </div>

  <div class="form-group">
    <p>
    <%= f.check_box :t_and_c_acepted %> Aceptar <a href="https://docs.google.com/document/d/1pKWN24TRAmfWPMLVq43y6kWTpEKiEmqaRuhHzTdfYk4/edit?usp=sharing">terminos y condiciones</a>
    </p>
  </div>

  <div class="actions">
    <%= f.submit 'ORDENAR', class: "btn btn-lg btn-default" %>
  </div>
<% end %>
</fieldset>

app/views/general_users/orders/_rate_form.html.erb
<fieldset>
<%= form_for([current_user, order]) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :overall_quality, t(:overall_quality) %>
    <%= rating_for @order, "overall_quality", star_path: '/images' %>
  </div>

  <div class="field">
    <%= f.label :comment_rate, t(:comment_rate) %><br>
    <%= f.text_area :comment_rate %>
  </div>

  <div class="actions">
    <%= f.submit t(:rate_order) %>
  </div>
<% end %>
</fieldset>

app/views/general_users/orders/_table.html.erb
<% if orders.any? %>
<div class="table-responsive">
<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Menu</th>
      <th>Cocinero</th>
      <th>Estado</th>
      <th>Entrega</th>
    </tr>
  </thead>

  <tbody>
    <% orders.each do |order| %>
      <tr>
        <td><%= link_to order.id, [current_user, order] %></td>
        <td><%= order.name %></td>
        <td><%= order.household_name %></td>
        <td><%= order.state %></td>
        <td><%= order.delivery_eta %> en <%= order.address %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<% else %>
  <p>No hay ordenes</p>
<% end %><%# ./if.orders.any %>


<%= paginate orders %>

app/views/general_users/orders/index.html.erb
<div class="container">
<h1>Listing Orders</h1>

<%= render 'table', orders: @orders %>
</div>

app/views/general_users/orders/show.html.erb
<div class="container">

<h2>Orden de <%= @menu.name %></h2>
Por <%= @menu.by_name %>

<p>
  <strong>Hora estimada de entrega:</strong>
  <%= @menu.delivery_eta.to_s(:military) %>
</p>

<p>
  <strong>Estatus:</strong>
  <%= @order.state %>
</p>

<p>
  <strong>Información del pago</strong>
<ul>
  <% quantity = @order.quantity || 1 %>
  <li>Numero de ordenes: <%= quantity %></li>
  <li>Subtotal: $ <%= @menu.price * quantity %> MXN</li>
  <li>IVA: $ 0.00 MXN</li>
  <li>Total: $ <%= @menu.price * quantity %> MXN</li>
  <% payment = @order.payment %>
  <li>ID del pago: <%= payment.id if payment %></li>
  <li>ID de transacción: <%= payment.transaction_id if payment %></li>
</ul>
</p>


<p>
  <strong>Comentarios para la comida:</strong>
  <%= "No hay comentarios" unless @order.comment_food.size > 0 %>
  <%= @order.comment_food %>
</p>

<p>
  <strong>Comentarios para la orden:</strong>
  <%= "No hay comentarios" unless @order.comment_order.size > 0 %>
  <%= @order.comment_order %>
</p>

<% if current_general_user && @order.delivered? %>
  <%= render 'rate_form', order: @order %>
<% elsif current_general_user && @order.rated? %>
<p>
  <%= rating_for @order, "overall_quality", star_path: '/images' %>
  <strong>Comment order:</strong>
  <%= @order.comment_rate %>
</p>
<% end %>

<%= link_to 'Regresar', general_user_orders_path(current_user) %>
</div>